<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [33]:
import pandas as pd
import numpy as np

Load the dataset into a dataframe.

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

In [23]:
df.head(5)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [64]:
# your code goes here
df.duplicated().sum()

0

In [65]:
len(df.index)

11305

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [69]:
# your code goes here
df.drop_duplicates(keep=False, inplace=True)

Verify if duplicates were actually dropped.

In [68]:
# your code goes here
df.duplicated().sum()

0

In [66]:
df['Respondent'].drop_duplicates(keep=False, inplace=True)

In [70]:
df['Respondent'].unique().sum()

142069733

## Finding Missing values

Find the missing values for all columns.

In [71]:
# your code goes here
df.isna().sum().sum()

31486

Find out how many rows are missing in the column 'WorkLoc'

In [72]:
# your code goes here
df['WorkLoc'].isna().sum().sum()

0

In [73]:
df['WorkLoc'].head(5)

0                                              Home
1                                            Office
2                                              Home
3                                              Home
4    Other place, such as a coworking space or cafe
Name: WorkLoc, dtype: object

In [74]:
df['EdLevel'].isna().sum().sum()

110

In [75]:
df['Country'].isna().sum().sum()

0

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [76]:
# your code goes here
df['WorkLoc'].value_counts()

Office                                            6747
Home                                              3559
Other place, such as a coworking space or cafe     967
0                                                   32
Name: WorkLoc, dtype: int64

In [77]:
df['Employment'].value_counts()

Employed full-time    10880
Employed part-time      425
Name: Employment, dtype: int64

In [78]:
df['UndergradMajor'].value_counts()

Computer science, computer engineering, or software engineering          6894
Information systems, information technology, or system administration     787
Another engineering discipline (ex. civil, electrical, mechanical)        751
Web development or web design                                             406
A natural science (ex. biology, chemistry, physics)                       399
Mathematics or statistics                                                 370
A business discipline (ex. accounting, finance, marketing)                242
A social science (ex. anthropology, psychology, political science)        209
A humanities discipline (ex. literature, history, philosophy)             206
Fine arts or performing arts (ex. graphic design, music, studio art)      159
I never declared a major                                                  123
A health science (ex. nursing, pharmacy, radiology)                        24
Name: UndergradMajor, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [79]:
#make a note of the majority value here, for future reference
df.WorkLoc.mode()

0    Office
dtype: object

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [80]:
# your code goes here
df['WorkLoc'].fillna(0, inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [81]:
# your code goes here
df['WorkLoc'].isna().sum().sum()

0

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [82]:
# your code goes here
List_Of_Categories_In_Column=list(df['CompFreq'].value_counts().index)
List_Of_Categories_In_Column

['Yearly', 'Monthly', 'Weekly']

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [83]:
# your code goes here
df['NormalizedAnnualCompensation']=np.nan
annual=[]
def comp_norm():
    for x,y in zip(df['CompFreq'],df['CompTotal']):
        if x=='Monthly':
            annual.append(y*12)
        elif x=='Weekly':
            annual.append(y*52)
        else:
            annual.append(y)
comp_norm()
df['NormalizedAnnualCompensation'] = annual
df[['NormalizedAnnualCompensation']]

       NormalizedAnnualCompensation
0                           61000.0
1                          138000.0
2                           90000.0
3                          348000.0
4                           90000.0
...                             ...
11547                      130000.0
11548                       74400.0
11549                      105000.0
11550                       80000.0
11551                           NaN

[11305 rows x 1 columns]

In [84]:
df['CompFreq'].unique()

array(['Yearly', 'Monthly', 'Weekly', nan], dtype=object)

In [85]:
df.NormalizedAnnualCompensation.median()

100000.0

In [86]:
df['CompFreq'].value_counts()

Yearly     6018
Monthly    4753
Weekly      328
Name: CompFreq, dtype: int64

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).